import { useEffect } from 'react';
import styles from './styles.module.scss';
import Head from 'next/head';
import router from 'next/router';
export default function noMobile() {
  useEffect(() => {
    if (window.innerWidth < 768) {
      router.push('/');
    }
  }, [router]);
  return (
    <>
      <Head>
        <title>David & Rebeca&apos;s wedding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <h1 className={styles.title}>Website only for mobile devices.</h1>
      </div>
    </>
  );
}
