version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '80:3000'
    environment:
      - NEXT_PUBLIC_STRAPI_URL=http://backend:1337
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /app/data/data.db
    volumes:
      - ./backend/data:/app/data
