// Style imports
//import styles from '@/styles/Home.module.scss';
import Head from 'next/head';

import { Header } from '@/components/Header';

// Static data
const navLinks = [
  {
    href: '/',
    text: 'Home'
  },
  {
    href: '/rsvp',
    text: 'RSVP'
  },
  {
    href: '/#itinary',
    text: 'Itinary'
  }
];

export default function Home() {
  return (
    <>
      <Head>
        <title>David & Rebeca&apos;s wedding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header links={navLinks} />
    </>
  );
}
